### ISSUE TITLE
average_precision_at_k not working as intended

### ISSUE THREAD

**Issue by sushantMoon** [LucaCappelletti94/extra_keras_metrics#1]
I have been trying to get average_precision_at_k work with the yolo model written in keras.

The snippet of the code is 
```python
>>> model = create_model(
                input_shape,
                anchors,
                num_classes,
                freeze_body=2,
                weights_path=os.path.join(
                    weight_dir,
                    'trained_weights_final.h5'
                )
            )
>>> type(model)
<class 'keras.engine.training.Model'>
>>>
>>> model.compile(
...     optimizer=Adam(lr=1e-4),
...     loss={
...         'yolo_loss': lambda y_true, y_pred: y_pred
...     },
...     metrics=[average_precision_at_k(1)]
... )

Traceback (most recent call last):
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be at least rank 1 but is rank 0 for 'metrics_1/average_precision_at_k_1/average_precision_at_1/TopKV2' (op: 'TopKV2') with input shapes: [], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    File "<stdin>", line 6, in <module>
    File "C:\Users\DELL\Anaconda3\lib\site-packages\keras\engine\training.py", line 451, in compile
        handle_metrics(output_metrics)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\keras\engine\training.py", line 420, in handle_metrics
        mask=masks[i])
    File "C:\Users\DELL\Anaconda3\lib\site-packages\keras\engine\training_utils.py", line 404, in weighted
        score_array = fn(y_true, y_pred)
    File "<C:\Users\DELL\Anaconda3\lib\site-packages\decorator.py:decorator-gen-30>", line 2, in tmp
    File "C:\Users\DELL\Anaconda3\lib\site-packages\extra_keras_metrics\metric.py", line 13, in metric
        score = metric(labels, predictions)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\extra_keras_metrics\average_precision_at_k.py", line 22, in tmp
        **kwargs
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\ops\metrics_impl.py", line 3238, in average_precision_at_k
        _, predictions_idx = nn.top_k(predictions, k)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 3084, in top_k
        return gen_nn_ops.top_kv2(input, k=k, sorted=sorted, name=name)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 8401, in top_kv2
        "TopKV2", input=input, k=k, sorted=sorted, name=name)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
        op_def=op_def)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
        return func(*args, **kwargs)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
        op_def=op_def)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
        control_input_ops)
    File "C:\Users\DELL\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
        raise ValueError(str(e))
ValueError: Shape must be at least rank 1 but is rank 0 for 'metrics_1/average_precision_at_k_1/average_precision_at_1/TopKV2' (op: 'TopKV2') with input shapes: [], [].
```

Please let me know if I am using this wrongly. The code works fine without the metric `average_precision_at_k` from this module

**Comment by LucaCappelletti94** [comment]
Could you provide the model weights or the original model so that I may be able to reproduce the issue? The metric is tested within the test suit on a Keras model, so there is reason to believe that it works properly, and I'd like to extend the testing also to your model.

Thank you!

**Comment by sushantMoon** [comment]
The model that I am using is mostly written by [qqwweee](https://github.com/qqwweee/keras-yolo3), you can directly look into `train.py` script, the `_main()` function has all the calls that you can reuse/look while building the model. The weights used are [YOLO3.weights](https://pjreddie.com/media/files/yolov3.weights).

I have been trying to write the evaluations function for the same and hence was needing the metric.

Thank you for your quick response !
Great work !

**Comment by LucaCappelletti94** [comment]
I don't believe I will have soon the time to read the source code of the library you provided, could you provide a small snippet of code that produces the error, so that I might work on that?

Otherwise this might take quite a few days to solve just for the part of finding the time for understanding the library.

**Comment by sushantMoon** [comment]
Sure.

So after cloning [qqwweee/keras-yolo3](https://github.com/qqwweee/keras-yolo3), create the folder structure `logs\000` inside the cloned directory.

Download [yolo3.weights](https://pjreddie.com/media/files/yolov3.weights) to the cloned directory.

Using the terminal `cd` to the cloned directory, 

1. Convert the yolo weights to keras compatible format by running the following script from the cloned directory
`python convert.py yolov3.cfg yolov3.weights model_data/yolo_weights.h5`

2. Start python shell on the cloned directory and run the following commands
```python
from train import *
from extra_keras_metrics import average_precision_at_k

annotation_path = 'train.txt'
log_dir = 'logs/000/'
classes_path = 'model_data/voc_classes.txt'
anchors_path = 'model_data/yolo_anchors.txt'
class_names = get_classes(classes_path)
num_classes = len(class_names)
anchors = get_anchors(anchors_path)
input_shape = (416,416)

model = create_model(
    input_shape,
    anchors,
    num_classes,
    freeze_body=2,
    weights_path='model_data/yolo_weights.h5'
    )

model.compile(
    optimizer=Adam(lr=1e-4),
    loss={
        'yolo_loss': lambda y_true, y_pred: y_pred
    },
    metrics=[average_precision_at_k(1)]
)
```

With this you should be able to generate the same error.
Hope this helps. Thank You!

**Comment by LucaCappelletti94** [comment]
Some small updates: the issue presents itself with any metric imported from TensorFlow. I am trying to understand why the model fails to identify the input/output shapes, where are they defined?

**Comment by LucaCappelletti94** [comment]
So if I define the auroc function this way for instance:
```py
import tensorflow as tf
import silence_tensorflow
from keras import backend as K

def auroc(y_true, y_pred)->float:
    print(y_true.shape, y_pred.shape)
    print(y_true)
    print(y_pred)
    score = tf.metrics.auc(y_true, y_pred, curve="ROC", summation_method="careful_interpolation")[1]
    K.get_session().run(tf.local_variables_initializer())
    return score
```
and I try to apply it to:
```py
model.compile(
    optimizer=Adam(lr=1e-4),
    loss={
        'yolo_loss': lambda y_true, y_pred: y_pred
    },
    metrics=[auroc]
)
```
I get your error and the printed shape is:
```txt
(?, ?) ()
Tensor("yolo_loss_target_2:0", shape=(?, ?), dtype=float32)
Tensor("yolo_loss/add_17:0", shape=(), dtype=float32)
```
which honestly I still have to understand what that means, but tensorflow does not accept vectors with this shape as input.

**Comment by LucaCappelletti94** [comment]
So it means that the dimensions are not fixed in the graph and it can vary between run calls, but this would cause the metrics to become unreliable.

**Comment by sushantMoon** [comment]
@LucaCappelletti94 Thanks for your help, I finally figured out what the problem was over the weekend. The problem was due to how the layers were defined for training, turns out i can not use the function directly at the time of evaluation/training/testing due to how the training procedure is defined by @qqwweee.
Once again Thanks for all your help.
I believe we can close this issue.
